CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;
CREATE TABLE IF NOT EXISTS tracks (
 id TEXT PRIMARY KEY, metadata TEXT NOT NULL, source TEXT, rights TEXT,
 status TEXT NOT NULL DEFAULT 'available', duration DOUBLE PRECISION, path TEXT, error TEXT,
 downloaded_at DOUBLE PRECISION
);
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, created DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS user_sessions (digest TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires DOUBLE PRECISION NOT NULL);
CREATE INDEX IF NOT EXISTS user_session_expiry ON user_sessions(expires);
CREATE TABLE IF NOT EXISTS account_attempts (bucket TEXT NOT NULL, created DOUBLE PRECISION NOT NULL);
CREATE INDEX IF NOT EXISTS account_attempt_bucket ON account_attempts(bucket,created);
CREATE TABLE IF NOT EXISTS user_likes (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, track_id TEXT NOT NULL REFERENCES tracks(id), created DOUBLE PRECISION NOT NULL, PRIMARY KEY(user_id,track_id));
CREATE TABLE IF NOT EXISTS user_playlists (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, name TEXT NOT NULL, created DOUBLE PRECISION NOT NULL);
CREATE INDEX IF NOT EXISTS user_playlist_owner ON user_playlists(user_id);
CREATE TABLE IF NOT EXISTS user_playlist_tracks (playlist_id TEXT NOT NULL REFERENCES user_playlists(id) ON DELETE CASCADE, track_id TEXT NOT NULL REFERENCES tracks(id), position INTEGER NOT NULL, PRIMARY KEY(playlist_id,track_id));
CREATE TABLE IF NOT EXISTS personal_downloads (listener TEXT NOT NULL, created DOUBLE PRECISION NOT NULL);
CREATE INDEX IF NOT EXISTS personal_download_time ON personal_downloads(created);
CREATE TABLE IF NOT EXISTS failed_downloads (
 id TEXT PRIMARY KEY, job_id TEXT NOT NULL, track_id TEXT NOT NULL,
 kind TEXT NOT NULL, source_url TEXT, page_url TEXT, error_type TEXT NOT NULL,
 error_detail TEXT NOT NULL, created DOUBLE PRECISION NOT NULL, replacement_id TEXT,
 UNIQUE(job_id,track_id)
);
CREATE TABLE IF NOT EXISTS app_tokens (
 id TEXT PRIMARY KEY, name TEXT NOT NULL, digest TEXT NOT NULL UNIQUE,
 created DOUBLE PRECISION NOT NULL, last_used DOUBLE PRECISION, revoked DOUBLE PRECISION
);
CREATE TABLE IF NOT EXISTS playlist (
 position BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, track_id TEXT UNIQUE REFERENCES tracks(id), priority INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS plays (
 id TEXT PRIMARY KEY, track_id TEXT NOT NULL, metadata TEXT NOT NULL,
 starts DOUBLE PRECISION NOT NULL, ends DOUBLE PRECISION NOT NULL, actual_end DOUBLE PRECISION
);
CREATE TABLE IF NOT EXISTS outbox (
 id TEXT PRIMARY KEY, queue TEXT NOT NULL, body TEXT NOT NULL,
 created DOUBLE PRECISION NOT NULL, sent DOUBLE PRECISION, done DOUBLE PRECISION, failed TEXT
);
CREATE TABLE IF NOT EXISTS reactions (
 id TEXT PRIMARY KEY, play_id TEXT NOT NULL, listener TEXT NOT NULL, emoji TEXT NOT NULL,
 accepted DOUBLE PRECISION NOT NULL, metadata TEXT NOT NULL, processed INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS requests (
 sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id TEXT UNIQUE NOT NULL, listener TEXT NOT NULL,
 query TEXT NOT NULL, mode TEXT NOT NULL, response TEXT NOT NULL, track_id TEXT REFERENCES tracks(id),
 status TEXT NOT NULL, created DOUBLE PRECISION NOT NULL, play_id TEXT
);
CREATE INDEX IF NOT EXISTS request_pending ON requests(status,sequence);
CREATE TABLE IF NOT EXISTS conversations (listener TEXT PRIMARY KEY, genres TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS rag_embeddings (track_id TEXT PRIMARY KEY, model TEXT NOT NULL, digest TEXT NOT NULL, vector TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS rag_pending (listener TEXT PRIMARY KEY, genres TEXT NOT NULL, track_ids TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS rag_turns (id TEXT PRIMARY KEY, listener TEXT NOT NULL, created DOUBLE PRECISION NOT NULL, busy INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS announcements (id TEXT PRIMARY KEY, track_id TEXT NOT NULL, script TEXT NOT NULL, details TEXT NOT NULL, path TEXT NOT NULL, duration DOUBLE PRECISION NOT NULL, created DOUBLE PRECISION NOT NULL, voice TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS source_hosts (hostname TEXT PRIMARY KEY, provider TEXT NOT NULL, role TEXT NOT NULL, status TEXT NOT NULL, discovered_from TEXT, notes TEXT NOT NULL DEFAULT '', first_seen DOUBLE PRECISION NOT NULL, last_seen DOUBLE PRECISION NOT NULL, tracks_downloaded INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS host_downloads (track_id TEXT PRIMARY KEY, source_host TEXT NOT NULL, media_host TEXT, completed DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS crawl_frontier (url TEXT PRIMARY KEY, provider TEXT NOT NULL, genre TEXT, depth INTEGER NOT NULL DEFAULT 0, discovered_from TEXT, next_attempt DOUBLE PRECISION NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'pending', error TEXT);
CREATE TABLE IF NOT EXISTS crawl_runs (id TEXT PRIMARY KEY, started DOUBLE PRECISION NOT NULL, finished DOUBLE PRECISION, pages INTEGER NOT NULL DEFAULT 0, tracks INTEGER NOT NULL DEFAULT 0, errors INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS media_objects (object_key TEXT PRIMARY KEY, track_id TEXT NOT NULL, kind TEXT NOT NULL, path TEXT NOT NULL, mime TEXT NOT NULL, checked DOUBLE PRECISION);
CREATE TABLE IF NOT EXISTS track_visuals (track_id TEXT PRIMARY KEY, status TEXT NOT NULL, created DOUBLE PRECISION NOT NULL, submitted DOUBLE PRECISION, completed DOUBLE PRECISION, provider_id TEXT, artwork_source TEXT, artwork_key TEXT, video_key TEXT, error TEXT);
CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY, body TEXT NOT NULL, done INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS reaction_play ON reactions(play_id,processed);
CREATE INDEX IF NOT EXISTS play_time ON plays(ends);
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS intro_id TEXT REFERENCES announcements(id);
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS requested_intro_id TEXT REFERENCES announcements(id);
ALTER TABLE requests ADD COLUMN IF NOT EXISTS suggestions TEXT NOT NULL DEFAULT '[]';
ALTER TABLE requests ADD COLUMN IF NOT EXISTS sources TEXT NOT NULL DEFAULT '[]';
ALTER TABLE requests ADD COLUMN IF NOT EXISTS engine TEXT NOT NULL DEFAULT 'basic';
ALTER TABLE requests ADD COLUMN IF NOT EXISTS requested_genre TEXT NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS reaction_listener ON reactions(listener,accepted);
CREATE TABLE IF NOT EXISTS observer_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS observer_seen (id TEXT PRIMARY KEY, created DOUBLE PRECISION NOT NULL);
-- Opt-in sharing: no changes to existing user or playlist records.
CREATE TABLE IF NOT EXISTS listener_profiles (user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, display_name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS shared_playlists (playlist_id TEXT PRIMARY KEY REFERENCES user_playlists(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS listener_follows (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, followed_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, PRIMARY KEY(user_id,followed_id), CHECK(user_id<>followed_id));
CREATE TABLE IF NOT EXISTS playlist_follows (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, playlist_id TEXT NOT NULL REFERENCES shared_playlists(playlist_id) ON DELETE CASCADE, PRIMARY KEY(user_id,playlist_id));
CREATE INDEX IF NOT EXISTS listener_follow_target ON listener_follows(followed_id);
CREATE INDEX IF NOT EXISTS playlist_follow_target ON playlist_follows(playlist_id);
